title: Jervil Angelo De Leon
logo: /assets/img/headshot_circle.png
description: BSIT graduate and Onsite Technical Support Engineer with growing experience in troubleshooting, hardware/software support, and basic network administration. Iâ€™m currently preparing for the CCNA to strengthen my fundamentals in routing, switching, and network security.
#show_downloads: true
theme: jekyll-theme-minimal
